wandb_version: 1

model_name:
  desc: null
  value: seresnext
num_epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 32
dataset_number:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.9.10
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720960980
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.10
      5: 0.17.4
      8:
      - 1
      - 5
      13: darwin-x86_64
